### This is a YAML configuration file. It is loaded in the script
### VDI_4655.py, which is an implementation of the VDI 4655.
###
### This is an example config file that shows the available settings

settings:
    ### Input weather data, must be of the type 'IGS' or 'DWD'.
    ### TRY weather data downloaded from Deutscher Wetterdienst (DWD)
    ### (https://kunden.dwd.de/obt/) should work right away as type 'DWD'.
    weather_file:       ../resources_weather/TRY2010_04_Jahr.dat
    weather_data_type:  DWD

    ### Output file name, is saved to a 'Result' subfolder
    print_file:     Example_load.dat

    rename_columns:
        Q_Heiz_TT: E_th_RH
        Q_Kalt_TT: E_th_KL
        Q_TWW_TT: E_th_TWE
        Q_loss: E_th_loss
        W_TT: E_el

    ### Which columns do you want to include in the printed file?
    ### (Leaving this commented out gives all the available columns)
    # print_columns:  [HOUR, E_th_RH_HH, E_th_TWE_HH, E_el_HH, E_th_RH_GHD,
                     # E_th_TWE_GHD, E_el_GHD, E_th_KL_GHD, E_th_loss]

    ### Do you want to print the index (i.e. time stamp for each row)?
    ### Set this to 'False' for TRNSYS (It cannot handle the datetime index)
    # print_index:    True
    print_index:    False

    ### Display a plot of the energy demand types on screen when finished
    # show_plot:      True

    ### Time step used for interpolation, e.g. '15 minutes' or '1 hours'
#    intervall:      15 minutes
    intervall:      1 hours

    ### Start and ende date & time for interpolation
    start:          [2017,1,1,00,00,00]
    # end:            [2017,1,3,00,00,00]
    end:            [2018,1,1,00,00,00]

    ### Include a zero-filled first row for TRNSYS
    # include_zero_row: True

    ### Leapyears are a tricky thing. You can choose to delete February 29.
    ### with the following flag.
    ### Be aware: If your weather data only has 8760 hours and you choose a
    ### leap year, you won't have December 31.
    remove_leapyear:    False   # If True, delete February 29.

    ### Instead of the VDI's temperature dependent method to determine the
    ### season, you have the option to use the BDEW method with fixed dates:
    # use_BDEW_seasons: True

    ### The VDI 4655 default heat limit is 15°C (definition of summer days).
    ### For modern building types, this can be set to a lower value
    Tamb_heat_limit: 12
    # In addition to the Tamb_heat_limit, you may overwrite the VDI4655 and
    # set heat demand on all summer days to zero:
    zero_summer_heat_demand: True

    ### Use daily mean as constant value for domestic hot water
    # flatten_daily_TWE: True

    ### Activate the debugging flag to display more info in the terminal
    log_level: debug

### This section is not part of VDI 4655:
### In this section you can define the relevant input for the 'Heizkurve'.
### If 'Heizkurve' is commented out, these calculations are not performed
Heizkurve:
    T_VL_N:     75      # °C Vorlauf Nenntemperatur
    T_RL_N:     45      # °C Rücklauf Nenntemperatur
    T_i:        20      # °C Wohnraum Innentemperatur (20°C laut DIN V 18599-10)
    T_a_N:      -12     # °C Außen (Umgebung) Bezugs/Nenntemperatur
    # m:          0.45    # Heizflächenexponent: Plattenheizkörper / Konvektor
    m:          0.1     # Heizflächenexponent: Fußbodenheizung

### This section is not part of VDI 4655:
### Based on the following input, the heat loss from the pipes to the
### environment will be estimated (requires results from 'Heizkurve'):
### dTm         = (T_VL + T_RL)/2.0 - T_a
### Q_dot_loss  = 2 * length * loss_coefficient * dTm
Verteilnetz:
    diameter_inner:     0.05    # m       Inner pipe diameter
    length:             6565    # m       Length of pipes (one-way)
    loss_coefficient:   0.26808 # W/(m*K) Heat loss per meter pipe length and K
    # loss_total_kWh:     1.19461 # kWh (Optional: fit of loss_coefficient)


### You can use the following factors to adjust any (or none) of the annual
### energy demand values. This helps scale the demand to a desired value
#adjustment_factors:
#    f_Q_Heiz:   1.17
#    f_Q_TWW:    1.17
#    f_W:        .8

### You can normalize all results to a total of 1 kWh per year.
# normalize: True

### In this section of the configuration file, you must define at least one (or
### as many more as you like) houses to calculate the energy demand for.
### The 'copies' key can create additinal copies of that house.
### The 'sigma' key can apply a time shift to the original energy profile,
### where the given integer describes the standard deviation of the normal
### distribution. Its unit is 'time steps'. Example: With an 'interval' of
### 15 min and a deviation of sigma = 2 time steps, 68% of profiles are
### shifted up to ±30 min (±1σ). 27% of proflies are shifted ±30 to 60 min
### (±2σ) and another 4% are shifted ±60 to 90 min (±3σ).
###
### Available selections for 'house_type':
### - EFH: Einfamilienhaus
### - MFH: Mehrfamilienhaus
### - G1G: BDEW Gebäude "Büro" (Gewerbe werktags 8:00 – 18:00 Uhr)
### - G4G: BDEW Gebäude "Handel" (Läden aller Art, Öffnungszeiten Werktag bis
###        abends, Samstag bis nachmittags)

houses:
    EFH:
        Q_Heiz_a:       6000    # kWh, Jährlicher Heizenergieverbrauch
        # Q_TWW_a:        2290    # kWh, Jährliche Energiemenge Trinkwarmwasser
        # W_a:            3467    # kWh, Jährlicher Strombedarf
        TRY:            4       # TRY region
        house_type:     EFH
        N_Pers:         3       # Anzahl Personen
        N_WE:           1       # Anzahl Wohneinheiten
        copies:         24      # Added Copies. Can be randomized with 'sigma'
        sigma:          4     # Standard deviation of normal distribution

    MFH:
        Q_Heiz_a:       60000   # kWh, Jährlicher Heizenergieverbrauch
        # Q_TWW_a:        35031   # kWh, Jährliche Energiemenge Trinkwarmwasser
        # W_a:            35658   # kWh, Jährlicher Strombedarf
        TRY:            4       # TRY region
        house_type:     MFH
        N_Pers:         45      # Anzahl Personen
        N_WE:           15      # Anzahl Wohneinheiten
        copies:         24      # Added Copies. Can be randomized with 'sigma'
        sigma:          2     # Standard deviation of normal distribution

    Buero:
        Q_Heiz_a:       50000   # kWh, Jährlicher Heizenergieverbrauch
        Q_Kalt_a:       7000    # kWh, Jährlicher Kältebedarf
        Q_TWW_a:        1500    # kWh, Jährliche Energiemenge Trinkwarmwasser
        W_a:            60000   # kWh, Jährlicher Strombedarf
        house_type:     G1G
        copies:         4
        sigma:          1
    Handel:
        Q_Heiz_a:       100000  # kWh, Jährlicher Heizenergieverbrauch
        Q_Kalt_a:       43000   # kWh, Jährlicher Kältebedarf
        Q_TWW_a:        4500    # kWh, Jährliche Energiemenge Trinkwarmwasser
        W_a:            110000  # kWh, Jährlicher Strombedarf
        house_type:     G4G
        copies:         9
        sigma:          1

