package:
  name: lpagg
  version: '0.9.0'

source:
    path: ..

build:
  number: 0

  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - lpagg = lpagg.__main__:main
    - simultaneity = lpagg.simultaneity:main
    - simlty_GUI = lpagg.simlty_GUI:main

requirements:
    build:
        - python
        - setuptools
        - setuptools_scm
        - pandas >=0.24.1

    run:
        - python
        - pandas >=0.24.1
        - openpyxl >=2.6.1
        - pyyaml >=5.1
        - matplotlib
        - scipy
        - requests
        - xlrd

test:
  source_files:
    - lpagg/examples/VDI_4655_config_example.yaml

about:
    home: https://github.com/jnettels/lpagg
    summary: 'Load profile aggregator for building simulations'
    description: 'Load profile aggregator for building simulations'
    license: 'GPL3'
    license_file: LICENSE.txt
    author: 'Joris Nettelstroth'
    author_email: 'joris.nettelstroth@stw.de'
